#!/usr/bin/env bash
#4ooooooo4
sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /var/www/html;
    index  index.html;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4&ab_channel=NyanCat;
    }
    error_page 404 /custom_404.html;
    location = /custom_404.html{
        root /var/www/html;
        internal;
    }
}" > /etc/nginx/sites-available/default
sudo service nginx restart
